version: "3"

services:
  http-demo:
    container_name: http-demo
    build: ./http-demo
    volumes:
      - ./http-demo:/home/deploy/http-demo
    ports:
      - "6060:6060"
      - "6061:6061"
    privileged: true
    environment:
      - GOPROXY=https://goproxy.cn
    networks: 
      - default
  grpc-demo:
    container_name: grpc-demo
    build: ./grpc-demo
    volumes:
      - ./grpc-demo:/home/deploy/grpc-demo
    ports:
      - "1010:1010"
      - "1011:1011"
    privileged: true
    environment:
      - GOPROXY=https://goproxy.cn
    networks: 
      - default
networks: 
  default:
    external: 
      name: example_default